### ISSUE TITLE
in README-MAVEN.md

### ISSUE THREAD

**Issue by beep02** [kevin-wayne/algs4#2]
1) backslash with apostrophe ,like in c:\\some-highlited-maven-dir  , must be 
replaced by 2 backslashes and apostrophe \\\\' , otherwise text is corrupted

this error can be present in all explanations about windows.
in linux we have forward slash.

2) different lines  - one under another - visible as single line in resulting text.

to really separate lines, you need 2-ce press return at the end of the line.

It is important in text, where command line params set, PATH, M2_HOME, etc... commands must be separated.

**Comment by kevin-wayne** [comment]
Yes, I think it’s better to make this a .txt file so that programmers can cut and paste the command more easily. I reorganized the document a bit. I think the goal should be to explain how to use Maven to produce algs4-<version>.jar from each environment (that we want to support). Perhaps we should also include the git command for command line users.

We can assume the programmer has already installed Java and their favorite IDE.

I think I added you (beep02) as a collaborator.

> On Sep 1, 2015, at 8:18 AM, Peter K. <notifications@github.com> wrote:
> 
> 1) backslash with apostrophe ,like in c:\some-highlited-maven-dir , must be 
> replaced by 2 backslashes and apostrophe \\' , otherwise text is corrupted
> 
> this error can be present in all explanations about windows.
> in linux we have forward slash.
> 
> 2) different lines - one under another - visible as single line in resulting text.
> 
> to really separate lines, you need 2-ce press return at the end of the line.
> 
> It is important in text, where command line params set, PATH, M2_HOME, etc... commands must be separated.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
