### ISSUE TITLE
StdRandom.java,  gaussian( ), polar form, closed interval [-1,+1]

### ISSUE THREAD

**Issue by 0017031** [kevin-wayne/algs4#41]
Excuse me for being a little pedantic...

In the function _gaussian( )_: 
_uniform(-1.0, 1.0)_ is called to generate the uniformly distributed values of x and y.  

The polar form of the Box-Muller transform requires x and y to be in the **closed** interval [−1.0, +1.0].
Whereas, the output of _uniform(-1.0, 1.0)_ is **half-open** interval [-1.0, +1.0).

**Comment by kevin-wayne** [comment]
I agree that this is a subtle detail that should be checked. In this case, however, I don’t think it matters whether the output of uniform(-1.0, 1.0) is open, closed, or half-open because Box-Muller will reject any x or y that is exactly -1.0 or 1.0. That is, Box-Muller doesn’t really require x and y to be chosen from a closed interval.

> On Nov 27, 2017, at 4:05 AM, 0017031 <notifications@github.com> wrote:
> 
> Excuse me for being a little pedantic...
> 
> In the function gaussian( ):
> uniform(-1.0, 1.0) is called to generate the uniformly distributed values of x and y.
> 
> The polar form of the Box-Muller transform requires x and y to be in the closed interval [−1.0, +1.0].
> Whereas, the output of uniform(-1.0, 1.0) is half-open interval [-1.0, +1.0).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by 0017031** [comment]
Yes. Kevin. I agree with you that the x=1 or y=1 case is rejected by the "r>=1" detection.
Thank you very much for the discussion.
